import type { Metadata } from "next";
import { ubuntu } from "./style/fonts/fonts";
import "./globals.scss";
import Header from "./_components/header/Header";
import Navigation from "./_components/header/navigation/Navigation";
// import Footer from "./_components/footer/Footer";

export const metadata: Metadata = {
  title: {
    template: "%s | XTREME FITNESS", // %s will be replaced by the current page title (%s looks for a string)
    default: "XTREME FITNESS",
  },
  description: "Generated by E-Thon for a final school project creating XTREME FITNESS webpage",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" className={ubuntu.variable}>
      <body
        className="antialiased">
        <Header>
          <Navigation />
        </Header>
        <main className="main">
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
