import type { Metadata } from "next";
import { ubuntu, teko } from "./style/fonts/fonts";
import "./globals.scss";

export const metadata: Metadata = {
  title: {
    template: "%s | XTREME FITNESS", // %s will be replaced by the current page title (%s looks for a string)
    default: "XTREME FITNESS",
  },
  description: "Generated by E-Thon for a final school project creating XTREME FITNESS webpage",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" className={`${ubuntu.variable} ${teko.variable}`}>
      <body
        className="antialiased">
        {children}
      </body>
    </html>
  );
}
